#!/usr/bin/env python3
"""
Dockerfile Generator for ARM Cross-Compilation Environments
Generates Dockerfile from YAML configuration files.
"""

import os
import sys
import yaml
import argparse
from pathlib import Path
from typing import Dict, List, Any


class DockerfileGenerator:
    """Generates Dockerfile from configuration."""
    
    def __init__(self, config_path: str):
        self.config_path = Path(config_path)
        self.config = self._load_config()
        
    def _load_config(self) -> Dict[str, Any]:
        """Load YAML configuration file."""
        if not self.config_path.exists():
            raise FileNotFoundError(f"Config file not found: {self.config_path}")
        
        with open(self.config_path, 'r') as f:
            return yaml.safe_load(f)
    
    def validate_config(self) -> List[str]:
        """Validate configuration and return list of errors."""
        errors = []
        required_fields = ['name', 'base_image', 'architecture']
        
        for field in required_fields:
            if field not in self.config:
                errors.append(f"Missing required field: {field}")
        
        # Validate toolchain configuration
        if 'toolchain' in self.config:
            toolchain = self.config['toolchain']
            if 'prefix' not in toolchain:
                errors.append("Toolchain configuration missing 'prefix'")
        
        return errors
    
    def generate(self) -> str:
        """Generate Dockerfile content from configuration."""
        lines = []
        
        # Header
        lines.extend(self._generate_header())
        lines.append("")
        
        # Base image
        lines.append(f"FROM {self.config['base_image']}")
        lines.append("")
        
        # Labels
        lines.extend(self._generate_labels())
        lines.append("")
        
        # Environment variables
        lines.extend(self._generate_env())
        lines.append("")
        
        # Package installation
        lines.extend(self._generate_packages())
        lines.append("")
        
        # Toolchain environment setup
        lines.extend(self._generate_toolchain_env())
        lines.append("")
        
        # Custom steps
        lines.extend(self._generate_custom_steps())
        lines.append("")
        
        # Final setup
        lines.extend(self._generate_final())
        
        return '\n'.join(lines)
    
    def _generate_header(self) -> List[str]:
        """Generate Dockerfile header comments."""
        name = self.config.get('name', 'unknown')
        arch = self.config.get('architecture', 'unknown')
        desc = self.config.get('description', f'{arch} cross-compilation environment')
        
        return [
            f"# {desc}",
            f"# Generated from config: {self.config_path.name}",
            f"# Architecture: {arch}",
            "#",
            "# DO NOT EDIT THIS FILE DIRECTLY",
            "# Modify the source config and regenerate",
        ]
    
    def _generate_labels(self) -> List[str]:
        """Generate LABEL instructions."""
        labels = [
            f"LABEL name=\"{self.config.get('name', 'unknown')}\"",
            f"LABEL architecture=\"{self.config.get('architecture', 'unknown')}\"",
        ]
        
        if 'description' in self.config:
            labels.append(f"LABEL description=\"{self.config['description']}\"")
        
        return labels
    
    def _generate_env(self) -> List[str]:
        """Generate ENV instructions."""
        lines = ["# Set environment variables"]
        
        env_vars = self.config.get('env', {})
        for key, value in env_vars.items():
            lines.append(f"ENV {key}={value}")
        
        return lines
    
    def _generate_packages(self) -> List[str]:
        """Generate package installation instructions."""
        lines = ["# Install packages"]
        lines.append("RUN apt-get update && apt-get install -y \\")
        
        packages = self.config.get('packages', {})
        all_packages = []
        
        # Collect all packages from categories
        for category in ['base', 'dev', 'qemu', 'libs', 'python']:
            if category in packages:
                all_packages.extend(packages[category])
        
        # Add toolchain packages
        if 'toolchain' in self.config and 'packages' in self.config['toolchain']:
            all_packages.extend(self.config['toolchain']['packages'])
        
        # Remove duplicates while preserving order
        seen = set()
        unique_packages = []
        for pkg in all_packages:
            if pkg not in seen:
                seen.add(pkg)
                unique_packages.append(pkg)
        
        # Format package list
        for i, pkg in enumerate(unique_packages):
            suffix = " \\" if i < len(unique_packages) - 1 else ""
            lines.append(f"    {pkg}{suffix}")
        
        lines.append("    && rm -rf /var/lib/apt/lists/*")
        
        return lines
    
    def _generate_toolchain_env(self) -> List[str]:
        """Generate toolchain environment variables."""
        if 'toolchain' not in self.config:
            return []
        
        toolchain = self.config['toolchain']
        prefix = toolchain.get('prefix', '')
        
        if not prefix:
            return []
        
        lines = ["# Set cross-compilation toolchain environment"]
        lines.append(f"ENV CROSS_COMPILE={prefix}-")
        lines.append(f"ENV CC={prefix}-gcc")
        lines.append(f"ENV CXX={prefix}-g++")
        lines.append(f"ENV AR={prefix}-ar")
        lines.append(f"ENV AS={prefix}-as")
        lines.append(f"ENV LD={prefix}-ld")
        lines.append(f"ENV RANLIB={prefix}-ranlib")
        lines.append(f"ENV STRIP={prefix}-strip")
        
        return lines
    
    def _generate_custom_steps(self) -> List[str]:
        """Generate custom installation steps."""
        custom_steps = self.config.get('custom_steps', [])
        
        if not custom_steps:
            return []
        
        lines = ["# Custom installation steps"]
        for step in custom_steps:
            lines.append(f"RUN {step}")
        
        return lines
    
    def _generate_final(self) -> List[str]:
        """Generate final Dockerfile instructions."""
        return [
            "# Set working directory",
            "WORKDIR /workspace",
            "",
            "# Default command",
            'CMD ["/bin/bash"]',
        ]
    
    def save(self, output_path: str) -> None:
        """Save generated Dockerfile to file."""
        content = self.generate()
        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output, 'w') as f:
            f.write(content)
        
        print(f"Generated: {output}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate Dockerfile from configuration'
    )
    parser.add_argument(
        'config',
        help='Path to configuration file (YAML)'
    )
    parser.add_argument(
        '-o', '--output',
        help='Output Dockerfile path (default: auto-generated)'
    )
    parser.add_argument(
        '--validate-only',
        action='store_true',
        help='Only validate config, do not generate'
    )
    
    args = parser.parse_args()
    
    try:
        generator = DockerfileGenerator(args.config)
        
        # Validate configuration
        errors = generator.validate_config()
        if errors:
            print("Configuration errors:")
            for error in errors:
                print(f"  - {error}")
            sys.exit(1)
        
        print(f"Configuration valid: {args.config}")
        
        if args.validate_only:
            return
        
        # Determine output path
        if args.output:
            output_path = args.output
        else:
            # Auto-generate path based on config name
            config_name = Path(args.config).stem
            output_path = f"dockerfiles/generated/{config_name}/Dockerfile"
        
        # Generate Dockerfile
        generator.save(output_path)
        print("Generation successful!")
        
    except FileNotFoundError as e:
        print(f"Error: {e}")
        sys.exit(1)
    except yaml.YAMLError as e:
        print(f"YAML parsing error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
